# Generated by Django 5.0.3 on 2024-03-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('state', models.IntegerField(default=0)),
                ('resume', models.TextField(blank=True, null=True)),
                ('started_conversation', models.BooleanField(default=False)),
                ('task', models.CharField(max_length=320)),
                ('conversation', models.JSONField(blank=True, default=dict, null=True)),
                ('conversation_summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
