# Generated by Django 5.0.3 on 2024-03-18 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_persona', models.TextField()),
                ('description', models.CharField(max_length=350)),
                ('task', models.CharField(choices=[('question_creator', 'Question Creator'), ('scorer', 'Scorer'), ('personality_judge', 'Personality Judge')], max_length=20)),
                ('agent_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.IntegerField(default=3)),
                ('question_base', models.CharField(max_length=350)),
                ('scoring_strategy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('retry', models.IntegerField(default=3)),
                ('score', models.IntegerField(default=0)),
                ('score_reasoning', models.TextField()),
                ('answer', models.TextField()),
                ('user_id', models.IntegerField()),
                ('base_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.basequestion')),
            ],
        ),
    ]
